function [ ...
    Eta_UGlobal, ...
    Eta_PhiGlobal, ...
    Eta_u, ...
    Eta_phi, ...
    Eta_mix] = ...
    verfurthIndicatorAT2( ...
    mesh,u,phi,H,material,model,quad, ...
    dir_nodes,crack_nodes)
% ==============================================================
% VERFÜRTH ESTIMATOR FOR AT2
%
% Computes:
%
%   Eta_u
%   Eta_phi
%   Eta_mix
%
% together with global displacement and phase-field estimators.
% ==============================================================


%% --------------------------------------------------------------
% Dimension check
% --------------------------------------------------------------

dim = model.dim;

if dim ~= mesh.meta.dim

    error( ...
        'model.dim (%d) does not match mesh.meta.dim (%d).', ...
        dim,mesh.meta.dim);

end


%% ==============================================================
% PHASE-FIELD INDICATOR
% ==============================================================

if dim == 2

    [~,Eta_phi,~] = ...
        phi2DResidualIndicator( ...
        mesh, ...
        phi, ...
        H, ...
        material, ...
        model, ...
        quad, ...
        crack_nodes);

else

    [~,Eta_phi,~] = ...
        ResidualIndicator_Phi_AT2_mesh3D( ...
        mesh, ...
        phi, ...
        H, ...
        material, ...
        model, ...
        quad, ...
        crack_nodes);

end


%% ==============================================================
% DISPLACEMENT INDICATOR
% ==============================================================

if dim == 2

    [~,Eta_u,~] = ...
        u2DResidualIndicator( ...
        mesh, ...
        u, ...
        phi, ...
        material, ...
        model, ...
        quad, ...
        dir_nodes);

else

    [~,Eta_u,~] = ...
        ResidualIndicator_U_AT2_mesh3D( ...
        mesh, ...
        u, ...
        phi, ...
        material, ...
        model, ...
        quad, ...
        dir_nodes);

end


%% ==============================================================
% MIXED INDICATOR
% ==============================================================

Eta_mix = ...
    sqrt(Eta_u.^2 + Eta_phi.^2);


%% ==============================================================
% GLOBAL INDICATORS
% ==============================================================

Eta_UGlobal = ...
    sqrt(sum(Eta_u.^2));

Eta_PhiGlobal = ...
    sqrt(sum(Eta_phi.^2));

end